language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "philipparndt-github"
    token:
      secure: "T/eQC+6d6MoXxDgjkax8H8a8F0OKXPlfivRg23sLYIlD0jHnMM++71QlhIkOqSLDG+KIeLZKg7wdI1xF+Dr04y6PGrKstg2CJ1ftAk/DPm0DIfctTrsSGTqHNfVLsVm8+2h3htRsqL2zRnQgaOsqzjZJw7S2DU6C31DL5lw8pKWJgrhHtQn5lKbmvsLyQH62VtNfynzWURKPV/hEClqHbwocE6egQ4wMrLARivLowyC37aFS7bv7jLTy8QkXsJJe29P2OpwdjUUV7MwJisEiva0i2XxudgtTFV0CHCb5q1KeApg62+S9dEK9G+H2+Fcnz/7XPY3NDqxM3vOpdgf6RVqv94zwQGeQzJv/tAN/DdDb0viNOpR08yzClTqsLhdeSNU1oxPMq+J7p8+IgRex6fQiLILgcJXiPE+S/calN0YDP11tHTJqkEkNaxPomA1bgWfG4pdMWR3rcz+rptJ0jsbcpGzdndo1PIH5k4xXbxbW3f9qALAUqpTAcrUJbdFxvqprtrjECnRvgpmmIJZLXiN+WZvZdfJVRCQbp6WGAOMNNh8WSad1eTomroHtiWy3jEaYhcT71dlHseIeiJmsjNc/HBHSlXbcqFWFMnjH+GuxMhfFkSy9af5HUNw3CRmRNFT89fvc3d86S3wK1BHaaWqkA+fIUiXQ9onVd/VBQZk="

jdk:
  - oraclejdk8

before_install: cd de.rnd7.calexport

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
